# Generated by Django 4.2.16 on 2026-05-02 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_club_options_alter_coach_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='coach',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='competitionedition',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='formation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='lineupentry',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='matchevent',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='playerskills',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='stadium',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tactic',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'managed': True},
        ),
    ]
