# Generated by Django 4.2.16 on 2026-05-02 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_club_options_alter_coach_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='season',
            table='season',
        ),
    ]
